import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import CustomAntdConfigProvider from "@/providers/CustomAntdConfigProvider";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { AuthenticationProvider } from "@/providers/AuthenticationProvider";
import { Suspense } from "react";
import { AlertMessageProvider } from "@/providers/AlertMessageProvider";
import { AlertNotificationProvider } from "@/providers/AlertNotificationProvider";

const mitr = Mitr({
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-mitr",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food Ordering Mini Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mitr.variable} h-full antialiased`}>
      <body className="min-h-full">
        <ReactQueryProvider>
          <AuthenticationProvider>
            <Suspense>
              <AntdRegistry>
                <CustomAntdConfigProvider>
                  <AlertNotificationProvider>
                    <AlertMessageProvider>{children}</AlertMessageProvider>
                  </AlertNotificationProvider>
                </CustomAntdConfigProvider>
              </AntdRegistry>
            </Suspense>
          </AuthenticationProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
